version: '3.3'
services:
  yt-convert-service:
    environment:
      - API_KEY=YOUR_API_KEY_HERE
    build: .
    restart: unless-stopped
    volumes:
      - yt-api-webfiles:/var/www/html
    ports:
      - '80:80'

volumes:
  yt-api-webfiles:
